language: node_js
node_js:
- '10'
os: linux
sudo: enabled
services:
- docker
env:
  global:
  - TRAVIS_ALLOW_FAILURE=false
install:
- npm install
before_script:
- mkdir ~/.aws
- mkdir kube
- cp credentials ~/.aws/
- curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.3.0/heptio-authenticator-aws_0.3.0_linux_amd64
- chmod +x aws-iam-authenticator
- sudo mv aws-iam-authenticator /usr/local/bin
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- cp kubeconfig kube/
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
#- cp travis.env .env
#- cat .env
###- mkdir logs
- CI=false npm run build
# - npm run test
after_success:
# - npm run coverage no

deploy:
- provider: script
  skip_cleanup: true
  script: 
    - bash deploy.sh
  on:
    all_branches: true
